# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: jSherz.com
author: James Sherwood-Jones
email: james@jsherz.com
description: > # this means to ignore newlines until "baseurl:"
  James Sherwood-Jones' collection of snippets, tips and tutorials.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jsherz.com" # the base hostname & protocol for your site
github_username: jSherz
linkedin_username: jsherz
cdk_course_link: https://www.udemy.com/course/aws-cdk-in-typescript/?couponCode=CDK-WITH-JSJ-2024-01

# Build settings
markdown: kramdown
include: ['assets/*']
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
