# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sherz' Blog
email: james.sherwoodjones@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Every time I can't get something open source working, there's a blog
  post with instructions on how to fix the issue. Time for me to give
  something back!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jsherz.com" # the base hostname & protocol for your site
twitter_username: TheSherz
github_username:  jSherz

# Build settings
markdown: kramdown
