name: 'Website'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    name: 'deploy'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.1
          bundler-cache: true

      - name: Build
        run: bundle exec jekyll build

      - name: Authenticate with AWS
        if: github.ref == 'refs/heads/main'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::262312054792:role/jsherz-com-github-actions
          aws-region: eu-west-1

      - name: Sync files to S3
        if: github.ref == 'refs/heads/main'
        run: |
          aws s3 sync \
            --metadata-directive REPLACE \
            --cache-control "max-age=86400" \
            _site/ s3://jsj-prod-jsherz-com-website/

      - name: Clear cache
        if: github.ref == 'refs/heads/main'
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions | jq --raw-output '.DistributionList.Items | map(select((.Aliases.Quantity >= 1) and (.Aliases.Items | contains(["jsherz.com"])))) | .[0].Id')

          export PAGER=""
          aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --path '/*'
